### ISSUE TITLE
Websites that require sign-in? 

### ISSUE THREAD

**Issue by sarahbohr** [sarahbohr/AbsoluteBeginnerProjects#1]
I'm going back and forth on whether to include websites that require the user to be signed in before they can do the project. There are probably great projects out there that are behind a sign-in and I don't want people to miss out on them. On the other hand, I dislike the idea of people having to trade their information to learn. Would love to hear some opinions.

**Comment by practicingdev** [comment]
Maybe include them but mark them as such in the guide?

**Comment by sarahbohr** [comment]
I think that's what I've decided to do. Thanks! Closed.
